import FavoriteOutlinedIcon from "@mui/icons-material/FavoriteOutlined";
import RecommendIcon from "@mui/icons-material/Recommend";

const posts = [
  {
    id: 1,
    image: "/images/user1.jpeg",
    name: "Janell Shrum",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my first post",
    postedDate: "1 day ago",
    postedImage: "/images/user1.jpeg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 12,
    comment: "10 comments",
  },
  {
    id: 2,
    image: "/images/user2.webp",
    name: "Alex Durden",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my second post",
    postedDate: "14 minutes ago",
    postedImage: "/images/user2.webp",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 241,
    comment: "501 comments",
  },
  {
    id: 3,
    image: "/images/user3.jpg",
    name: "Dora Hawks",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my third post",
    postedDate: "3 days ago",
    postedImage: "/images/user3.jpg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 41,
    comment: "100 comments",
  },
  {
    id: 4,
    image: "/images/user4.webp",
    name: "Robert Downey",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my fourth post",
    postedDate: "10 months ago",
    postedImage: "/images/user4.webp",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 475,
    comment: "200 comments",
  },
  {
    id: 5,
    image: "/images/user5.jpg",
    name: "Rocky Balboa",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my fifth post",
    postedDate: "1 year ago",
    postedImage: "/images/user5.jpg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 578,
    comment: "300 comments",
  },
  {
    id: 6,
    image: "/images/user6.jpg",
    name: "Bruce Banner",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my sixth post",
    postedDate: "3 months ago",
    postedImage: "/images/user6.jpg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 201,
    comment: "400 comments",
  },
  {
    id: 7,
    image: "/images/user7.jpg",
    name: "Tony Stark",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my seventh post",
    postedDate: "2 weeks ago",
    postedImage: "/images/user7.jpg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 258,
    comment: "500 comments",
  },
  {
    id: 8,
    image: "/images/user8.jpg",
    name: "Steve Rogers",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my eighth post",
    postedDate: "30 days ago",
    postedImage: "/images/user8.jpg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 324,
    comment: "600 comments",
  },
  {
    id: 9,
    image: "/images/user9.jpg",
    name: "Jill Doe",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my ninth post",
    postedDate: "9 days ago",
    postedImage: "/images/user9.jpg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 487,
    comment: "700 comments",
  },
  {
    id: 10,
    image: "/images/user10.jpg",
    name: "Bruce Wayne",
    ellipsisImage: "/images/e.svg",
    postTagText: "This is my tenth post",
    postedDate: "10 minutes ago",
    postedImage: "/images/user10.jpg",
    likeIcon: <RecommendIcon />,
    loveIcon: <FavoriteOutlinedIcon />,
    like: 254,
    comment: "800 comments",
  },
].sort(() => Math.random() - 0.5);
export default posts;
